package org.ual.hmis.equipo16;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ListadoIncorrectoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
	    System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe"); 
	    System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe"); 
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void listadoIncorrecto() {
		// Test name: listadoIncorrecto
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://ecovivarenas.es/");
		// 2 | setWindowSize | 1552x840 |
		driver.manage().window().setSize(new Dimension(1552, 840));
		if (!driver.findElements(By.id("btn-aceptar-cookies")).isEmpty()) {
			driver.findElement(By.id("btn-aceptar-cookies")).click();
		}
		// 3 | click | linkText=Verduras |
		driver.findElement(By.linkText("Verduras")).click();
		// 4 | click | id=precioMenor |
		driver.findElement(By.id("precioMenor")).click();
		// 5 | type | id=precioMenor | 3
		driver.findElement(By.id("precioMenor")).sendKeys("3");
		// 6 | click | id=precioMayor |
		driver.findElement(By.id("precioMayor")).click();
		// 7 | type | id=precioMayor | 2
		driver.findElement(By.id("precioMayor")).sendKeys("2");
		// 8 | click | css=.filtro:nth-child(2) |
		driver.findElement(By.cssSelector(".filtro:nth-child(2)")).click();
		// 9 | assertElementNotPresent | css=.producto:nth-child(1) > .datosProducto
		// input:nth-child(1) |
		{
			List<WebElement> elements = driver
					.findElements(By.cssSelector(".producto:nth-child(1) > .datosProducto input:nth-child(1)"));
			assert (elements.size() == 0);
		}
		// 10 | assertElementNotPresent | css=.producto:nth-child(2) > .datosProducto
		// input:nth-child(1) |
		{
			List<WebElement> elements = driver
					.findElements(By.cssSelector(".producto:nth-child(2) > .datosProducto input:nth-child(1)"));
			assert (elements.size() == 0);
		}
	}
}
